on:
  push:
    tags:
      - "**"

name: "Publish Release"

jobs:
  publish-release:
    name: "Publish Release"

    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          coverage: none
          extensions: none
          tools: none

      - name: "Determine tag"
        run: echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: "Download script to extract notes"
        run: |
          mkdir build
          chmod -R g+w build
          cd build
          wget https://raw.githubusercontent.com/ericsizemore/ericsizemore/main/scripts/extract-release-notes.php

      - name: "Parse ChangeLog"
        run: php build/extract-release-notes.php ${{ env.RELEASE_TAG }} > RELEASE_NOTES.md

      - name: "Create release"
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.RELEASE_TAG }}
          name: ${{ env.RELEASE_TAG }}
          bodyFile: RELEASE_NOTES.md
